### ISSUE TITLE
2.12-ification

### ISSUE THREAD

**Issue by mosesn** [twitter/ostrich#74]
In order to support 2.12, we need to add crossScalaVersions to Build.scala, and make sure everything compiles.  Not every scala library will be built against the current snapshot, so we may have to support different versions from 2.11 to 2.12.  If part of an API has churned (scalacheck in particular is susceptible to this) we may need to upgrade the 2.11 library version to make progress.  If that happens, contact me (@mosesn) and I'll navigate the upgrade for you–it's a little complicated because we will need to upgrade all of our internal libraries, not just scrooge.  Please note that most of this upgrade will not be feasible until we have a portion of util already upgraded.

**Comment by idarlington** [comment]
Hi @mosesn , for its dependencies on util-eval, util-core, util-logging, util-jvm is there plan to use snapshots or the latest version available in the repo.

It seems their snapshots are not available.

**Comment by mosesn** [comment]
@idarlington you can make local snapshots by cloning the util repo and doing `./sbt +publishLocal`.  We have instructions in [CONTRIBUTING.md][0] files for most of our projects, but we never set one up for `ostrich` because it's deprecated.  We still need to support it for now though, which is why we're making this change =) so maybe it would make sense to consider adding it.

Let me know if you still have problems!

[0]: https://github.com/twitter/scrooge/blob/develop/CONTRIBUTING.md

**Comment by jeffreyolchovy** [comment]
Feel free to checkout this branch and publish a local artifact to resolve your 2.12.x dependency on scala-json https://github.com/twitter/scala-json/pull/1

**Comment by mosesn** [comment]
@jeffreyolchovy so I poked around, and I think we might be able to kill scala-json if we add a dependency on a different json lib.

@idarlington are you still working on this?  would you be interested in tackling moving us from scala-json to jackson?

**Comment by idarlington** [comment]
Hi @mosesn , I am still on it, had a busy week but I should be able to wrap things up before net week.

**Comment by idarlington** [comment]
Hi, @mosesn I have committed the changes, similar to what @jeffreyolchovy did in the util project.

**Comment by mosesn** [comment]
@idarlington thanks!  Yeah, I saw and commented on the PR =)  Thanks!  I think there might be a little more work to do, but definitely a solid start.

**Comment by mosesn** [comment]
this was merged in way back https://github.com/twitter/ostrich/commit/1a819b1fb76740fd81348c6e484fe5abed69ffe7 thanks @idarlington!
