### ISSUE TITLE
dealphabetize ostrich stats json

### ISSUE THREAD

**Issue by landism** [twitter/ostrich#78]
Ostrich depends on scala-json, which always produces json with keys in alpha order.
As part of killing scala-json, I am moving Ostrich to use Jackson. It is possible that a consumer of Ostrich has taken a dependency on the fact that its json keys are in alpha order.

Since I don't want to block killing scala-json on deciding/verifying whether it's safe to change this behavior, I've simply had Jackson emit json in alpha order as well.

This ticket is to consider actually deciding/verifying that it's safe to change the alpha behavior remove the sorting.

Feel free to WontFix this. I've mostly just filed this ticket because I thought this was too long to put directly in the code.

**Comment by mosesn** [comment]
My feeling is that ostrich is deprecated so it's fine to not care about this.  We can revive it if folks start running into perf issues.
